### ISSUE TITLE
add a step to installation instructions?

### ISSUE THREAD

**Issue by emilyville** [jlord/gs2geojson#5]
Before running "npm test", I think there should be a step to run "npm install", otherwise npm test will fail because it can't find tabletop.

**Comment by jlord** [comment]
WHOOPS! You actually don't even need to run `npm test` unless you've cloned this repo and are just trying out the script. Since it is an NPM module now, you don't have to clone this repo, you just do the global install and can run the command line stuff from wherever you are in Terminal. Thanks for catching this @emilyville! :heart_decoration:
